FDMC.App/Models/BindingModels/CatCreatingBindingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FDMC.App.Models.BindingModels
{
    public class CatCreatingBindingModel
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public string Breed { get; set; }

        public string ImageUrl { get; set; }
    }
}

FDMC.App/Models/ErrorViewModel.cs
using System;

namespace FDMC.App.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FDMC.App/Models/ViewModels/CatConciseViewModel.cs
namespace FDMC.App.Models.ViewModels
{
    public class CatConciseViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

FDMC.App/Models/ViewModels/CatDetailsViewModel.cs
namespace FDMC.App.Models.ViewModels
{
    public class CatDetailsViewModel
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public string Breed { get; set; }

        public string ImageUrl { get; set; }
    }
}

FDMC.App/Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FDMC.App.Models.BindingModels;
using FDMC.App.Models.ViewModels;
using FDMC.Data;
using FDMC.Models;
using Microsoft.AspNetCore.Mvc;

namespace FDMC.App.Controllers
{
    public class CatsController : Controller
    {

        public CatsController(FDMCAppDbContext context)
        {
            this.Context = context;
        }

        public FDMCAppDbContext Context { get; set; }

        public IActionResult Details(int id)
        {
            var cat = this.Context.Cats.Find(id);

            if (cat == null)
            {
                return NotFound();
            }
            var catModel = new CatDetailsViewModel()
            {
                Age = cat.Age,
                Breed = cat.Breed,
                ImageUrl = cat.ImageUrl,
                Name = cat.Name
            };

            

            return View(model: catModel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Add(CatCreatingBindingModel model)
        {
            var cat = new Cat()
            {
                Age = model.Age,
                Breed = model.Breed,
                ImageUrl = model.ImageUrl,
                Name = model.Name
            };
            this.Context.Cats.Add(cat);
            this.Context.SaveChanges();

            //return RedirectToRoute(
            //    "default",
            //    new { controller = "Cats", Action = "Details", Id = model.Id });

            return RedirectToAction("Details", new {id=cat.Id});
        }
    }
}

FDMC.App/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using FDMC.App.Models;
using FDMC.App.Models.ViewModels;
using FDMC.Data;

namespace FDMC.App.Controllers
{
    public class HomeController : Controller
    {

        public HomeController(FDMCAppDbContext context)
        {
            this.Context = context;
        }

        public FDMCAppDbContext Context { get; private set; }

        public IActionResult Index()
        {
            var cats = this.Context.Cats
                .Select(cat => new CatConciseViewModel()
                {
                    Id = cat.Id,
                    Name = cat.Name
                })
                .ToArray();

            return View(cats);
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FDMC.App/Views/Cats/Add.cshtml
@model FDMC.App.Models.BindingModels.CatCreatingBindingModel
@{
    ViewData["Title"] = "Add";
}

<h1>Add Cat</h1>

<form action="/Cats/Add" method="post">
    <p>
        <div class="form-group">
            <label asp-for="Name" style=""></label>
            <br/>
            <input type="text" name="Name" value=""/>
        </div>
    </p>
    <div class="form-group">
        <label asp-for="Age"></label>
        <br />
        <input type="text" name="Age" value="" />
    </div>
    <div class="form-group">
        <label asp-for="Breed"></label>
        <br />
        <input type="text" name="Breed" value="" />
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl">Image URL</label>
        <br />
        <input type="text" name="ImageUrl" value="" />
    </div>
    <div class="form-group" >
        <input type="submit" value="Add cat"/>
    </div>
</form>

FDMC.App/Views/Cats/Details.cshtml
@model FDMC.App.Models.ViewModels.CatDetailsViewModel
@{
    ViewData["Title"] = "Details for " + Model.Name;
}

<h2 align="center">Details for @Model.Name</h2>

<div><img src="@Model.ImageUrl" alt="Picture for @Model.Name"  style="max-width: 300px"/></div>

<div>
    <strong>Name: </strong> @Model.Name
</div>
<div>
    <strong>Age: </strong> @Model.Age
</div>
<div>
    <strong>Breed: </strong> @Model.Breed
</div>

FDMC.App/Views/Home/Index.cshtml
@model IEnumerable<FDMC.App.Models.ViewModels.CatConciseViewModel>

@{
    ViewData["Title"] = "Home Page";
}

<h1 align="center">Fluffy Duffy Munchkin Cats</h1>

<ul>
    @foreach (var cat in Model)
    {
        <li><a asp-controller="Cats" asp-action="Details" asp-route-id="@cat.Id">@cat.Name</a></li>
    }
</ul>

FDMC.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FDMC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FDMC</a>
                <a class="navbar-brand" asp-area="" asp-controller="Cats" asp-action="Add">Add Cat</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>